chats/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'chats'

urlpatterns = [
    path('send/',       views.send,       name='send'),
    path('receive/',    views.receive,    name='receive'),
    path('attachment/', views.attachment, name='attachment'),
]

gettingstarted/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import Index

from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

import hello.views

urlpatterns = [
    # path("", hello.views.index, name="index"),
    # path("db/", hello.views.db, name="db"),
    path('',       Index.as_view(), name="home"),
    path('chat/',  include('chats.urls', namespace="chats")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

katahack/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('',       views.index, name="home"),
    path('chat/',  include('chats.urls', namespace="chats")),
    path('admin/', admin.site.urls),
]

chats/models.py
from django.db import models
from django.conf import settings

class Chat(models.Model):
    user            = models.CharField(max_length=100)
    message         = models.TextField()
    attachment      = models.ImageField(upload_to='images/attachment/')
    is_sent         = models.SmallIntegerField()
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user

hello/models.py
from django.db import models

# Create your models here.
class Greeting(models.Model):
    when = models.DateTimeField("date created", auto_now_add=True)

chats/forms.py
from django import forms
from .models import Chat

class ChatForm(forms.ModelForm):
    attachment = forms.ImageField()
    user       = forms.CharField(widget=forms.HiddenInput(), initial="user", required=False)
    message    = forms.CharField(widget=forms.HiddenInput(), initial="-", required=False)
    is_sent    = forms.IntegerField(widget=forms.HiddenInput(), initial=0, required=False)

    class Meta:
        model  = Chat
        fields = ['attachment', 'user', 'message', 'is_sent']

chats/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from .models import Chat
# from django.core.serializers import serialize

from io import BytesIO
from PIL import Image
import requests
import pytesseract

def send(request): 
    chat = Chat.objects
    if request.method == 'POST':
        chat.create(
            user = "user",
            message = request.POST['message'],
            is_sent = 1
        )

        url      = 'https://kanal.kata.ai/receive_message/b2541886-e3b7-4de3-96c7-9cb06c0acc58'
        # url      = 'https://kanal.kata.ai/receive_message/b2541886-e3b7-4de3-96c7-9cb06c0acc58?token=RayleighPlasma'
        # url      = endpoint.format(source_lang='en', word_id=word)
        headers  = {'Content-Type': 'application/json', 'Accept': 'application/json', 'Authorization' : 'Bearer RayleighPlasma'}
        response = requests.get(url, headers=headers)

        chat.create(
            user = "admin",
            message = response,
            is_sent = 0
        )

        # kataResponse = serialize('json', response)

        # return JsonResponse({'user' : request.POST['message'], 'admin' : kataResponse})
        return HttpResponse(request.POST['message'])
        # return HttpResponse(response)
    
    return HttpResponse('error')

def receive(request): 
    if request.method == 'POST':
        types  = request.POST['type']
        chatss = Chat.objects.filter(user = "admin", is_sent = 0)

        if chatss.count() :
            for chat in chatss :
                chat.is_sent = 1
                chat.save()

                return HttpResponse(chat.message)

        return HttpResponse('')
    
    return HttpResponse('error')

def attachment(request):
    if request.method == 'POST':
        chats = Chat.objects.filter(user = "user", is_sent = 0)

        if chats.count() :
            for chat in chats :
        
                if chat.attachment :
                    # pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
                    response   = requests.get("https://warm-citadel-64062.herokuapp.com" + chat.attachment.url)
                    # response   = requests.get("http://localhost:5000" + chat.attachment.url)
                    img        = Image.open(BytesIO(response.content))
                    transcript = pytesseract.image_to_string(img)
                    
                    chat.message = transcript
                    chat.is_sent = 1
                    chat.save()

                    url      = 'https://kanal.kata.ai/receive_message/b2541886-e3b7-4de3-96c7-9cb06c0acc58'
                    # url      = 'https://kanal.kata.ai/receive_message/b2541886-e3b7-4de3-96c7-9cb06c0acc58?token=RayleighPlasma'
                    # url      = endpoint.format(source_lang='en', word_id=word)
                    headers  = {'Content-Type': 'application/json', 'Accept': 'application/json', 'Authorization' : 'Bearer RayleighPlasma', 'type' : 'text'}
                    response = requests.get(url, headers=headers)

                    responseChat = Chat.objects
                    responseChat.create(
                        user = "admin",
                        message = response,
                        is_sent = 0
                    )

                    return JsonResponse({'transcript' : transcript, 'img_url' : chat.attachment.url})

            return HttpResponse('')
            # return HttpResponse(chats.attachment.url)
			
        return HttpResponse('')
    
    return HttpResponse('error')

hello/views.py
import requests
from django.shortcuts import render
from django.http import HttpResponse

from .models import Greeting

# Create your views here.
# def index(request):
#     # return HttpResponse('Hello from Python!')
#     return render(request, "index.html")

def index(request):
    r = requests.get('http://httpbin.org/status/418')
    print(r.text)
    return HttpResponse('<pre>' + r.text + '</pre>')


def db(request):

    greeting = Greeting()
    greeting.save()

    greetings = Greeting.objects.all()

    return render(request, "db.html", {"greetings": greetings})

templates/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<title>Plasma Chat</title>
		<link rel="shortcut icon" href="{% static 'images/plasma.ico' %}" type="image/x-icon">

		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">

		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery.form.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.min.js' %}"></script>
	</head>
	<!--Coded With Love By Mutiullah Samim-->
	<body>
		<div class="container-fluid h-100">
			<div class="row justify-content-center h-100">  
				<div class="col-md-8 col-xl-6 chat">
					<div class="card">
						<div class="card-header msg_head">
							<div class="d-flex bd-highlight">
								<div class="img_cont">
									<img src="{% static 'images/plasma.png' %}" class="rounded-circle user_img">
									<span class="online_icon"></span>
								</div>
								<div class="user_info">
									<span>Chat with Plasma</span>									
								</div>
								<div class="video_cam">
								</div>
							</div>
						</div>
						<div class="card-body msg_card_body">
							{% for chat in chat_list %}
								{% if chat.user == "admin" %}
									<div class="d-flex justify-content-start mb-4">
										<div class="img_cont_msg">
											<img src="{% static 'images/plasma.png' %}" class="rounded-circle user_img_msg">
										</div>
										<div class="msg_cotainer">
											{% if chat.attachment %}
												<img src="{{ chat.attachment.url }}" width="150px" height="auto">
											{% else %}
												{{ chat.message }}
											{% endif %}
											<!-- <span class="msg_time">{{ chat.created_at }}</span>  -->
										</div>
									</div>
								{% else %}
								<div class="d-flex justify-content-end mb-4">
									<div class="msg_cotainer_send">
										{% if chat.attachment %}
											<img src="{{ chat.attachment.url }}" width="150px" height="auto">
										{% else %}
											{{ chat.message }}
										{% endif %}
										<!-- <span class="msg_time_send">{{ chat.created_at }}</span>  -->
									</div>

									<div class="img_cont_msg">
										<img src="{% static 'images/user.png' %}" class="rounded-circle user_img_msg">
									</div>
								</div>
								{% endif %}
							{% endfor %}
						</div>
						<div class="card-footer">
							<div class="input-group">
								<div class="input-group-append">
									<input type="file" id="image_to_upload" class="hidden" accept="image/png, image/jpeg"/>
									<span class="input-group-text attach_btn"><i class="fa fa-paperclip"></i></span>
								</div>
								{% csrf_token %}
								<textarea name="" class="form-control type_msg" placeholder="Type your message..."></textarea>
								<div class="input-group-append">
									<span class="input-group-text send_btn"><i class="fa fa-location-arrow"></i></span>
								</div>
							</div>
						</div>

						<form id="myForm" action="{% url 'home' %}" method="post" class="hidden"> 
							{% csrf_token %}
							{{ form.as_p }}
							<input type="submit" value="submit" id="submit_btn"/> 
						</form>
					</div>
				</div>

				<div class="footer col-md-12 justify-content-center">
					Template by <a href="https://bootsnipp.com/snippets/nNg98">https://bootsnipp.com/snippets/nNg98</a>
				</div>
			</div>
		</div>
	
		
		<script type="text/javascript">
		
			function getCookie(name) {
				var cookieValue = null;
				if (document.cookie && document.cookie !== '') {
					var cookies = document.cookie.split(';');
					for (var i = 0; i < cookies.length; i++) {
						var cookie = cookies[i].trim();
						// Does this cookie string begin with the name we want?
						if (cookie.substring(0, name.length + 1) === (name + '=')) {
							cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
							break;
						}
					}
				}
				return cookieValue;
			}

			function imageMsg(message) {
				return '<div class="d-flex justify-content-end mb-4">' +
								'<div class="msg_cotainer_send">' + 
									`<img src="` + message + `" width="150px" height="auto">` + 
								'</div>' +
								'<div class="img_cont_msg">' +
									`<img src="{% static 'images/user.png' %}" class="rounded-circle user_img_msg">` +
								'</div>' + 
							'</div>';
			}

			function userMsg(message) {
				return '<div class="d-flex justify-content-end mb-4">' +
								'<div class="msg_cotainer_send">' + 
									message + 
								'</div>' +
								'<div class="img_cont_msg">' +
									`<img src="{% static 'images/user.png' %}" class="rounded-circle user_img_msg">` +
								'</div>' + 
							'</div>';
			}
									// `<span class="msg_time_send">` + message + `</span>` +

			function adminMsg(message) {
				return '<div class="d-flex justify-content-start mb-4">' +
								'<div class="img_cont_msg">' +
									`<img src="{% static 'images/plasma.png' %}" class="rounded-circle user_img_msg">` + 
								'</div>' + 
								'<div class="msg_cotainer">' + 
									message + 
								'</div>' +
							'</div>';
			}
									// `<span class="msg_time">` + message.created_at + `</span>` +

			var checkMsg = setInterval(function(){
				var csrfmiddlewaretoken = getCookie('csrftoken');
				var type = 'receive';

				$.ajax({
					type: 'POST',
					url: "{% url 'chats:receive' %}",
					data: { type, csrfmiddlewaretoken },
					success: function(done){
						if(done != ""){
							console.log(done);
							var message = done.replace("<", "");
							message = message.replace(">", "");
							var msg = adminMsg(message);

							$('.msg_card_body').append(msg);
							$('.type_msg').val('');
						}
					},
					error: function(fail){
						console.log(fail.responseText);
					}
				});
			}, 5000);

			$(document).ready(function(){
				$('.attach_btn').click(function(){
					$('#id_attachment').click();
				})

				$("#id_attachment").on("change", function() {
					$("#submit_btn").click();
				});

				$('#myForm').ajaxForm(function() { 
					var csrfmiddlewaretoken = getCookie('csrftoken');

					$.ajax({
						type: 'POST',
						url: "{% url 'chats:attachment' %}",
						data: { csrfmiddlewaretoken },
						success: function(done){
							var img_msg = imageMsg(done.img_url);
							var msg = userMsg(done.transcript);
							// var admMsg = adminMsg(done.admin);

							$('.msg_card_body').append(img_msg);
							$('.msg_card_body').append(msg);
							// $('.msg_card_body').append(admMsg);
						},
						error: function(fail){
							console.log(fail.responseText);
						}
					});
				});

				$('.send_btn').click(function(){
					var csrfmiddlewaretoken = getCookie('csrftoken');
					var message = $('.type_msg').val();

					if(message != ""){
						$.ajax({
							type: 'POST',
							url: "{% url 'chats:send' %}",
							data: { message, csrfmiddlewaretoken },
							success: function(done){
								var msg    = userMsg(done);
								// var admMsg = adminMsg(done.admin);

								$('.msg_card_body').append(msg);
								// $('.msg_card_body').append(adminMsg);
								$('.type_msg').val('');
							},
							error: function(fail){
								console.log(fail.responseText);
							}
						});
					}
				});
            });
        </script>
	</body>
</html>